services:
  postgres:
    image: postgres:16-alpine
    container_name: vpn_master_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: vpn_core
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
