services:
  postgres:
    image: postgres:16-alpine
    container_name: vpn_master_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: 8d2db6862f66a3a3e81abd9e024f942b851f23a7d112fad9
      POSTGRES_DB: vpn_core
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pg_data:
